// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synap.Infrastructure.Persistence.Command;

#nullable disable

namespace Synap.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SynapDbContext))]
    [Migration("20260925151719_AddPasswordRecovery")]
    partial class AddPasswordRecovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Synap.Domain.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("note_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FechaCreacion")
                        .HasDatabaseName("idx_notes_user_created");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Synap.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Synap.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApiTokenCreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("api_token_created_at");

                    b.Property<string>("ApiTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("api_token_hash");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GroqApiKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("groq_api_key_encrypted");

                    b.Property<string>("GroqApiKeyLast4")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("groq_api_key_last4");

                    b.Property<DateTime?>("GroqApiKeyUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("groq_api_key_updated_at");

                    b.Property<string>("GroqModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("groq_model");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("password_reset_expires_at");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("password_reset_token_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("security_stamp");

                    b.HasKey("Id");

                    b.HasIndex("ApiTokenHash");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PasswordResetTokenHash");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("note_tags", b =>
                {
                    b.Property<Guid>("note_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tag_id")
                        .HasColumnType("uuid");

                    b.HasKey("note_id", "tag_id");

                    b.HasIndex("tag_id");

                    b.ToTable("note_tags", (string)null);
                });

            modelBuilder.Entity("Synap.Domain.Note", b =>
                {
                    b.OwnsOne("Synap.Domain.NoteMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("NoteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExtractedDescription")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("metadata_description");

                            b1.Property<string>("ExtractedTitle")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("metadata_title");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("metadata_image_url");

                            b1.HasKey("NoteId");

                            b1.ToTable("notes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NoteId");
                        });

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("note_tags", b =>
                {
                    b.HasOne("Synap.Domain.Note", null)
                        .WithMany()
                        .HasForeignKey("note_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synap.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
